name: SonarCloud Scan

on:
  workflow_run:
    workflows: ["Test Suite"]
    types:
      - completed

jobs:
  sonar:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .

      - uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.python.version=3.10
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=src/
            -Dsonar.tests=tests/
            -Dsonar.test.exclusions=tests/**
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
